---
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    show-sql: false
    open-in-view: false
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${DB_NAME:survey}"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "${MYSQL_USERNAME:root}"
    password: "${MYSQL_PASSWORD:}"
  application:
    name: "${NAME:survey}"
server:
  port: "${PORT:8080}"
