---
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
        format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:survey}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQLUSER:root}
    password: ${MYSQLPASSWORD:}
  application:
    name: ${NAME:survey}
server:
  port: ${PORT:8080}
